using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using TaskLog.Entities;

namespace TaskLog
{
    /// <summary>
    /// Логика взаимодействия для ComponentWindow.xaml
    /// </summary>
    public partial class ComponentWindow : Window
    {
        public Components ReturnedComponent { get; private set; }
        public ComponentWindow()
        {
            InitializeComponent();
            FillDataMainGrid();
        }

        private void AddComponentButton_Click(object sender, RoutedEventArgs e) // Обработчик нажатия на кнопку "AddComponentButton". Открывает окно создания компонента
        {
            AddComponentWindow addComponentWindow = new AddComponentWindow();
            bool? Result = addComponentWindow.ShowDialog();
            if (Result == true) 
            {
                FillDataMainGrid();
            }
        }
        public void FillDataMainGrid() // Функция заполнения MainDataGrid компонентами из базы данных
        {
            MainDataGrid.ItemsSource = DbUtils.db.Components.Select(p => new
            {
                p.CompId,
                p.CompOemId,
                p.CompOemVer,
                p.CompOemName,
                p.SwVer
            }).ToList();
        }

        private void FilteringButton_Click(object sender, RoutedEventArgs e) // Обработчик события нажатия на кнопку "FilteringButton". Заполняет MainDataGrid компонентами которые подходят по критериям введенным в поля для фильтрации
        {
            var dataComponents = DbUtils.db.Components.Select(p => new
            {
                p.CompId,
                p.CompOemId,
                p.CompOemVer,
                p.CompOemName,
                p.SwVer
            });

            if (!OemIdBox.Text.IsNullOrEmpty())
                dataComponents = dataComponents.Where(w => w.CompOemId.Contains(OemIdBox.Text));
            if (!OemVerBox.Text.IsNullOrEmpty())
                dataComponents = dataComponents.Where(w => w.CompOemVer.Contains(OemVerBox.Text));
            if (!OemNameBox.Text.IsNullOrEmpty())
                dataComponents = dataComponents.Where(w => w.CompOemName.Contains(OemNameBox.Text));
            if (!SwVerBox.Text.IsNullOrEmpty())
                dataComponents = dataComponents.Where(w => w.SwVer.Contains(SwVerBox.Text));

            MainDataGrid.ItemsSource = dataComponents.ToList();


        }

        private void MainDataGrid_AutoGeneratedColumns(object sender, EventArgs e) // Функция которая срабатывает после того как все колонки MainDataGrid заполнены, циклом проходит по всем колонкам и переводит каждую
        {
            foreach (var col in MainDataGrid.Columns)
            {
                col.Header = TranslatorForDataGridColumns.Translate(col.Header.ToString());
            }
        }

        private void MainDataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e) // Событие срабатывает после дойного нажатия на строку в MainDataGrid. Выбирает нажатую строку, помещает её в св-во ReturnedComponent и закрывает окно
        {
            if (MainDataGrid.SelectedCells.Count() == 0) return;
            var cellInfo = MainDataGrid.SelectedCells[0];
            int content = Convert.ToInt16((cellInfo.Column.GetCellContent(cellInfo.Item) as TextBlock).Text);
            var table = DbUtils.db.Components.Where(x => x.CompId == content).FirstOrDefault();
            if(table != null)
            {
                ReturnedComponent = table;
                this.DialogResult = true;
                this.Close();
            }
            else
            {
                MessageBox.Show("error");
                FillDataMainGrid();
                return;
            }
        }

        private void ClearFiltersButton_Click(object sender, RoutedEventArgs e) // Функция служит для очистки фильтров
        {
            OemIdBox.Text = "";
            OemVerBox.Text = "";
            OemNameBox.Text = "";
            SwVerBox.Text = "";
            FillDataMainGrid();
        }

        private void PreviousButton_Click(object sender, RoutedEventArgs e) // Закрывает это окно
        {
            this.Close();
        }
    }
}
