using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using TaskLog.Entities;

namespace TaskLog
{
    /// <summary>
    /// Логика взаимодействия для ComponentWindow.xaml
    /// </summary>
    public partial class ComponentWindow : Window
    {
        public ComponentWindow()
        {
            InitializeComponent();
            FillDataMainGrid();
        }

        private void AddComponentButton_Click(object sender, RoutedEventArgs e)
        {
            AddComponentWindow addComponentWindow = new AddComponentWindow();
            addComponentWindow.Show();
            this.Close();
        }
        public void FillDataMainGrid()
        {
            MainDataGrid.ItemsSource = DbUtils.db.Components.Select(p => new
            {
                p.CompOemId,
                p.CompOemVer,
                p.CompOemName,
                p.SwVer
            }).ToList();
        }

        private void MainDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var col in MainDataGrid.Columns)
            {
                col.Header = TranslatorForDataGridColumns.Translate(col.Header.ToString());
            }
        }
    }
}
