using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using TaskLog.Entities;

namespace TaskLog
{
    /// <summary>
    /// Логика взаимодействия для TasksWindow.xaml
    /// </summary>
    public partial class TasksWindow : Window
    {
        public TasksWindow()
        {
            InitializeComponent();
            FillDataMainGrid();
        }

        public void FillDataMainGrid()
        {
            MainDataGrid.ItemsSource = DbUtils.db.Tasks.Select(p => new
            {
                p.TaskId,
                DbUtils.db.Components.FirstOrDefault(x => x.CompId == p.CompId).CompOemName,
                DbUtils.db.Users.FirstOrDefault(x => x.UserId == p.UserId).UserName,
                DateTime = $"{DbUtils.db.EventLog.FirstOrDefault(x => x.TaskId == p.TaskId).EventTimestamp:f}",
                DbUtils.db.EventLog.Where(x => x.TaskId == p.TaskId).OrderByDescending(x => x.EventTimestamp).FirstOrDefault().EventType
            }).ToList();
        }

        private void SignOutButton_Click(object sender, RoutedEventArgs e)
        {
            MainWindow mainWindow = new MainWindow();
            mainWindow.Show();
            this.Close();
        }

        private void MainDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var col in MainDataGrid.Columns)
            {
                col.Header = TranslatorForDataGridColumns.Translate(col.Header.ToString());
            }
        }
    }
}
