using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using TaskLog.Entities;

namespace TaskLog
{
    /// <summary>
    /// Логика взаимодействия для TasksWindow.xaml
    /// </summary>
    public partial class TasksWindow : Window
    {
        public long UserId { get; set; }
        public TasksWindow()
        {
            InitializeComponent();
            FillDataMainGrid();
        }

        public void FillDataMainGrid()
        {
            MainDataGrid.ItemsSource = DbUtils.db.Tasks.Select(p => new
            {
                p.TaskId,
                DbUtils.db.Components.FirstOrDefault(x => x.CompId == p.CompId).CompOemName,
                DbUtils.db.Users.FirstOrDefault(x => x.UserId == p.UserId).UserName,
                DateTime = $"{DbUtils.db.EventLog.FirstOrDefault(x => x.TaskId == p.TaskId).EventTimestamp:f}",
                DbUtils.db.EventLog.Where(x => x.TaskId == p.TaskId).OrderByDescending(x => x.EventTimestamp).FirstOrDefault().EventType
            }).ToList();
        }

        private void SignOutButton_Click(object sender, RoutedEventArgs e)
        {
            MainWindow mainWindow = new MainWindow();
            mainWindow.Show();
            this.Close();
        }

        private void MainDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var col in MainDataGrid.Columns)
            {
                col.Header = TranslatorForDataGridColumns.Translate(col.Header.ToString());
            }
        }

        private void RefreshButton_Click(object sender, RoutedEventArgs e)
        {
            FillDataMainGrid();
        }

        private void MainDataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            var cellInfo = MainDataGrid.SelectedCells[0];
            int content = Convert.ToInt16((cellInfo.Column.GetCellContent(cellInfo.Item) as TextBlock).Text);
            var table = DbUtils.db.Tasks.Where(x => x.TaskId == content).FirstOrDefault();
            if (table != null) 
            {
                TaskViewWindow taskViewWindow = new TaskViewWindow(table);
                taskViewWindow.ShowDialog();
                RefreshButton_Click(sender, e);
            }
            else
            {
                MessageBox.Show("error");
                RefreshButton_Click(sender, e);
                return;
            }
        }

        private void AddTaskButton_Click(object sender, RoutedEventArgs e)
        {
            AddTaskWindow addTaskWindow = new AddTaskWindow();
            addTaskWindow.Show();
            addTaskWindow.UserId = UserId;
            this.Close();
        }
    }
}
